//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.17929.
// 

namespace FiverxLinkSecurityLib.Schema.V0200
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class apoInformation
  {

    private string apoIkField;

    private string rzKdNrField;

    private string apoSwHerstellerField;

    private string apoSwNameField;

    private string apoSwVersionField;

    private string apoLogMethodeField;

    private string apoInfoField;

    /// <remarks/>
    public string apoIk
    {
      get
      {
        return this.apoIkField;
      }
      set
      {
        this.apoIkField = value;
      }
    }

    /// <remarks/>
    public string rzKdNr
    {
      get
      {
        return this.rzKdNrField;
      }
      set
      {
        this.rzKdNrField = value;
      }
    }

    /// <remarks/>
    public string apoSwHersteller
    {
      get
      {
        return this.apoSwHerstellerField;
      }
      set
      {
        this.apoSwHerstellerField = value;
      }
    }

    /// <remarks/>
    public string apoSwName
    {
      get
      {
        return this.apoSwNameField;
      }
      set
      {
        this.apoSwNameField = value;
      }
    }

    /// <remarks/>
    public string apoSwVersion
    {
      get
      {
        return this.apoSwVersionField;
      }
      set
      {
        this.apoSwVersionField = value;
      }
    }

    /// <remarks/>
    public string apoLogMethode
    {
      get
      {
        return this.apoLogMethodeField;
      }
      set
      {
        this.apoLogMethodeField = value;
      }
    }

    /// <remarks/>
    public string apoInfo
    {
      get
      {
        return this.apoInfoField;
      }
      set
      {
        this.apoInfoField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/SV0100")]
  public partial class rzHashFunction
  {

    private string nameField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/SV0100")]
  public partial class rzEncryptionAlgorithm
  {

    private string nameField;

    private string[] modeField;

    private string[] paddingField;

    /// <remarks/>
    public string name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mode")]
    public string[] mode
    {
      get
      {
        return this.modeField;
      }
      set
      {
        this.modeField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("padding")]
    public string[] padding
    {
      get
      {
        return this.paddingField;
      }
      set
      {
        this.paddingField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/SV0100")]
  public partial class rzHandshake
  {

    private rzEncryptionAlgorithm[] rzEncryptionAlgorithmsField;

    private rzHashFunction[] rzHashfunctionsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rzEncryptionAlgorithms")]
    public rzEncryptionAlgorithm[] rzEncryptionAlgorithms
    {
      get
      {
        return this.rzEncryptionAlgorithmsField;
      }
      set
      {
        this.rzEncryptionAlgorithmsField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rzHashfunctions")]
    public rzHashFunction[] rzHashfunctions
    {
      get
      {
        return this.rzHashfunctionsField;
      }
      set
      {
        this.rzHashfunctionsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAnfrage
  {

    private apoInformation apoInformationField;

    private byte[] rzDatenBoxField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzDatenBox
    {
      get
      {
        return this.rzDatenBoxField;
      }
      set
      {
        this.rzDatenBoxField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAntwort
  {

    private string hinweisField;

    private byte[] rzDatenBoxField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzDatenBox
    {
      get
      {
        return this.rzDatenBoxField;
      }
      set
      {
        this.rzDatenBoxField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzZertifikatAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzZertifikatAntwort
  {

    private string hinweisField;

    private byte[] rzZertifikatField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzZertifikat
    {
      get
      {
        return this.rzZertifikatField;
      }
      set
      {
        this.rzZertifikatField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAktiviereApothekenZugangAnfrage
  {

    private apoInformation apoInformationField;

    private byte[] apoAktivierungsCodeField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] apoAktivierungsCode
    {
      get
      {
        return this.apoAktivierungsCodeField;
      }
      set
      {
        this.apoAktivierungsCodeField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAktiviereApothekenZugangAntwort
  {

    private string hinweisField;

    private byte[] pkcs12KeyStoreField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] pkcs12KeyStore
    {
      get
      {
        return this.pkcs12KeyStoreField;
      }
      set
      {
        this.pkcs12KeyStoreField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeVerlaengereApothekenZugangAnfrage
  {

    private apoInformation apoInformationField;

    private string apoIkField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    public string apoIk
    {
      get
      {
        return this.apoIkField;
      }
      set
      {
        this.apoIkField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeVerlaengereApothekenZugangAntwort
  {

    private string hinweisField;

    private byte[] pkcs12KeyStoreField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] pkcs12KeyStore
    {
      get
      {
        return this.pkcs12KeyStoreField;
      }
      set
      {
        this.pkcs12KeyStoreField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSecurityVersionAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSecurityVersionAntwort
  {

    private string hinweisField;

    private string rzSecurityVersionField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    public string rzSecurityVersion
    {
      get
      {
        return this.rzSecurityVersionField;
      }
      set
      {
        this.rzSecurityVersionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSicherheitsmerkmaleAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSicherheitsmerkmaleAntwort
  {

    private string hinweisField;

    private rzHandshake rzSicherheitsmerkmaleField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    public rzHandshake rzSicherheitsmerkmale
    {
      get
      {
        return this.rzSicherheitsmerkmaleField;
      }
      set
      {
        this.rzSicherheitsmerkmaleField = value;
      }
    }
  }
}
