//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityTestClient.FiveRxSecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fiverx.de/security/SV0100", ConfigurationName="FiveRxSecurityService.FiveRxLinkSecurityServiceSoap")]
    public interface FiveRxLinkSecurityServiceSoap {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="verarbeiteAuftragRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1 verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="verarbeiteAuftragRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1> verarbeiteAuftragAsync(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100")]
    public partial class verarbeiteAuftragRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private zweiParameterRequestMsg verarbeiteAuftragRequestMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public zweiParameterRequestMsg verarbeiteAuftragRequestMsg {
            get {
                return this.verarbeiteAuftragRequestMsgField;
            }
            set {
                this.verarbeiteAuftragRequestMsgField = value;
                this.RaisePropertyChanged("verarbeiteAuftragRequestMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class zweiParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        private string rzeLadeRzSecurityVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rzeLadeRzSecurityVersion {
            get {
                return this.rzeLadeRzSecurityVersionField;
            }
            set {
                this.rzeLadeRzSecurityVersionField = value;
                this.RaisePropertyChanged("rzeLadeRzSecurityVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class genericResponseMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeAusgabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeAusgabeDaten {
            get {
                return this.rzeAusgabeDatenField;
            }
            set {
                this.rzeAusgabeDatenField = value;
                this.RaisePropertyChanged("rzeAusgabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100/types")]
    public partial class verarbeiteAuftragResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private genericResponseMsg verarbeiteAuftragResponseMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public genericResponseMsg verarbeiteAuftragResponseMsg {
            get {
                return this.verarbeiteAuftragResponseMsgField;
            }
            set {
                this.verarbeiteAuftragResponseMsgField = value;
                this.RaisePropertyChanged("verarbeiteAuftragResponseMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag;
        
        public verarbeiteAuftragRequest1() {
        }
        
        public verarbeiteAuftragRequest1(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag) {
            this.requestAuftrag = requestAuftrag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100/types", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftragResponse;
        
        public verarbeiteAuftragResponse1() {
        }
        
        public verarbeiteAuftragResponse1(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftragResponse) {
            this.verarbeiteAuftragResponse = verarbeiteAuftragResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiveRxLinkSecurityServiceSoapChannel : FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiveRxLinkSecurityServiceSoapClient : System.ServiceModel.ClientBase<FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap>, FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap {
        
        public FiveRxLinkSecurityServiceSoapClient() {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1 FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 request) {
            return base.Channel.verarbeiteAuftrag(request);
        }
        
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag) {
            FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 inValue = new FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1();
            inValue.requestAuftrag = requestAuftrag;
            FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1 retVal = ((FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).verarbeiteAuftrag(inValue);
            return retVal.verarbeiteAuftragResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1> FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.verarbeiteAuftragAsync(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 request) {
            return base.Channel.verarbeiteAuftragAsync(request);
        }
        
        public System.Threading.Tasks.Task<FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse1> verarbeiteAuftragAsync(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag) {
            FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1 inValue = new FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest1();
            inValue.requestAuftrag = requestAuftrag;
            return ((FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).verarbeiteAuftragAsync(inValue);
        }
    }
}
