//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityLib.FiveRxSecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fiverx.de/security/SV0100", ConfigurationName="FiveRxSecurityService.FiveRxLinkSecurityServiceSoap")]
    public interface FiveRxLinkSecurityServiceSoap {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSecurityVersion weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="ladeRzSecurityVersionRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse1 ladeRzSecurityVersion(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest1 request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzZertifikat weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="ladeRzZertifikatRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse1 ladeRzZertifikat(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest1 request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSicherheitsmerkmale weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="ladeRzSicherheitsmerkmaleRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse1 ladeRzSicherheitsmerkmale(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest1 request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="verarbeiteAuftragRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse1 verarbeiteAuftrag(FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100")]
    public partial class ladeRzSecurityVersionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private einParameterRequestMsg ladeRzSecurityVersionRequestMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public einParameterRequestMsg ladeRzSecurityVersionRequestMsg {
            get {
                return this.ladeRzSecurityVersionRequestMsgField;
            }
            set {
                this.ladeRzSecurityVersionRequestMsgField = value;
                this.RaisePropertyChanged("ladeRzSecurityVersionRequestMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class einParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100/types")]
    public partial class verarbeiteAuftragResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private genericResponseMsg verarbeiteAuftragResponseMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public genericResponseMsg verarbeiteAuftragResponseMsg {
            get {
                return this.verarbeiteAuftragResponseMsgField;
            }
            set {
                this.verarbeiteAuftragResponseMsgField = value;
                this.RaisePropertyChanged("verarbeiteAuftragResponseMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class genericResponseMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeAusgabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeAusgabeDaten {
            get {
                return this.rzeAusgabeDatenField;
            }
            set {
                this.rzeAusgabeDatenField = value;
                this.RaisePropertyChanged("rzeAusgabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100")]
    public partial class verarbeiteAuftragRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private zweiParameterRequestMsg verarbeiteAuftragRequestMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public zweiParameterRequestMsg verarbeiteAuftragRequestMsg {
            get {
                return this.verarbeiteAuftragRequestMsgField;
            }
            set {
                this.verarbeiteAuftragRequestMsgField = value;
                this.RaisePropertyChanged("verarbeiteAuftragRequestMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class zweiParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        private string rzeLadeRzSecurityVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rzeLadeRzSecurityVersion {
            get {
                return this.rzeLadeRzSecurityVersionField;
            }
            set {
                this.rzeLadeRzSecurityVersionField = value;
                this.RaisePropertyChanged("rzeLadeRzSecurityVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100/types")]
    public partial class ladeRzSicherheitsmerkmaleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg {
            get {
                return this.ladeRzSicherheitsmerkmaleResponseMsgField;
            }
            set {
                this.ladeRzSicherheitsmerkmaleResponseMsgField = value;
                this.RaisePropertyChanged("ladeRzSicherheitsmerkmaleResponseMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100")]
    public partial class ladeRzSicherheitsmerkmaleRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg {
            get {
                return this.ladeRzSicherheitsmerkmaleRequestMsgField;
            }
            set {
                this.ladeRzSicherheitsmerkmaleRequestMsgField = value;
                this.RaisePropertyChanged("ladeRzSicherheitsmerkmaleRequestMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100/types")]
    public partial class ladeRzZertifikatResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private genericResponseMsg ladeRzZertifikatResponseMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public genericResponseMsg ladeRzZertifikatResponseMsg {
            get {
                return this.ladeRzZertifikatResponseMsgField;
            }
            set {
                this.ladeRzZertifikatResponseMsgField = value;
                this.RaisePropertyChanged("ladeRzZertifikatResponseMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100")]
    public partial class ladeRzZertifikatRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private zweiParameterRequestMsg ladeRzZertifikatRequestMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public zweiParameterRequestMsg ladeRzZertifikatRequestMsg {
            get {
                return this.ladeRzZertifikatRequestMsgField;
            }
            set {
                this.ladeRzZertifikatRequestMsgField = value;
                this.RaisePropertyChanged("ladeRzZertifikatRequestMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/SV0100/types")]
    public partial class ladeRzSecurityVersionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private genericResponseMsg ladeRzSecurityVersionResponseMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public genericResponseMsg ladeRzSecurityVersionResponseMsg {
            get {
                return this.ladeRzSecurityVersionResponseMsgField;
            }
            set {
                this.ladeRzSecurityVersionResponseMsgField = value;
                this.RaisePropertyChanged("ladeRzSecurityVersionResponseMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest requestSecurityVersion;
        
        public ladeRzSecurityVersionRequest1() {
        }
        
        public ladeRzSecurityVersionRequest1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest requestSecurityVersion) {
            this.requestSecurityVersion = requestSecurityVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100/types", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse ladeRzSecurityVersionResponse;
        
        public ladeRzSecurityVersionResponse1() {
        }
        
        public ladeRzSecurityVersionResponse1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse ladeRzSecurityVersionResponse) {
            this.ladeRzSecurityVersionResponse = ladeRzSecurityVersionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest requestladeRzZertifikat;
        
        public ladeRzZertifikatRequest1() {
        }
        
        public ladeRzZertifikatRequest1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest requestladeRzZertifikat) {
            this.requestladeRzZertifikat = requestladeRzZertifikat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100/types", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse ladeRzZertifikatResponse;
        
        public ladeRzZertifikatResponse1() {
        }
        
        public ladeRzZertifikatResponse1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse ladeRzZertifikatResponse) {
            this.ladeRzZertifikatResponse = ladeRzZertifikatResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest requestladeRzSicherheitsmerkmal;
        
        public ladeRzSicherheitsmerkmaleRequest1() {
        }
        
        public ladeRzSicherheitsmerkmaleRequest1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest requestladeRzSicherheitsmerkmal) {
            this.requestladeRzSicherheitsmerkmal = requestladeRzSicherheitsmerkmal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100/types", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmaleResponse;
        
        public ladeRzSicherheitsmerkmaleResponse1() {
        }
        
        public ladeRzSicherheitsmerkmaleResponse1(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmaleResponse) {
            this.ladeRzSicherheitsmerkmaleResponse = ladeRzSicherheitsmerkmaleResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag;
        
        public verarbeiteAuftragRequest1() {
        }
        
        public verarbeiteAuftragRequest1(FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag) {
            this.requestAuftrag = requestAuftrag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/SV0100/types", Order=0)]
        public FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftragResponse;
        
        public verarbeiteAuftragResponse1() {
        }
        
        public verarbeiteAuftragResponse1(FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftragResponse) {
            this.verarbeiteAuftragResponse = verarbeiteAuftragResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiveRxLinkSecurityServiceSoapChannel : FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiveRxLinkSecurityServiceSoapClient : System.ServiceModel.ClientBase<FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap>, FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap {
        
        public FiveRxLinkSecurityServiceSoapClient() {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse1 FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.ladeRzSecurityVersion(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest1 request) {
            return base.Channel.ladeRzSecurityVersion(request);
        }
        
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse ladeRzSecurityVersion(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest requestSecurityVersion) {
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest1 inValue = new FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionRequest1();
            inValue.requestSecurityVersion = requestSecurityVersion;
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSecurityVersionResponse1 retVal = ((FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).ladeRzSecurityVersion(inValue);
            return retVal.ladeRzSecurityVersionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse1 FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.ladeRzZertifikat(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest1 request) {
            return base.Channel.ladeRzZertifikat(request);
        }
        
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse ladeRzZertifikat(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest requestladeRzZertifikat) {
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest1 inValue = new FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatRequest1();
            inValue.requestladeRzZertifikat = requestladeRzZertifikat;
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzZertifikatResponse1 retVal = ((FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).ladeRzZertifikat(inValue);
            return retVal.ladeRzZertifikatResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse1 FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.ladeRzSicherheitsmerkmale(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest1 request) {
            return base.Channel.ladeRzSicherheitsmerkmale(request);
        }
        
        public FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmale(FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest requestladeRzSicherheitsmerkmal) {
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest1 inValue = new FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleRequest1();
            inValue.requestladeRzSicherheitsmerkmal = requestladeRzSicherheitsmerkmal;
            FiverxLinkSecurityLib.FiveRxSecurityService.ladeRzSicherheitsmerkmaleResponse1 retVal = ((FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).ladeRzSicherheitsmerkmale(inValue);
            return retVal.ladeRzSicherheitsmerkmaleResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse1 FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.verarbeiteAuftrag(FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest1 request) {
            return base.Channel.verarbeiteAuftrag(request);
        }
        
        public FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftrag(FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest requestAuftrag) {
            FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest1 inValue = new FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragRequest1();
            inValue.requestAuftrag = requestAuftrag;
            FiverxLinkSecurityLib.FiveRxSecurityService.verarbeiteAuftragResponse1 retVal = ((FiverxLinkSecurityLib.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).verarbeiteAuftrag(inValue);
            return retVal.verarbeiteAuftragResponse;
        }
    }
}
