//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityTestClient.ZertifikatService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientCertificate", Namespace="http://schemas.datacontract.org/2004/07/ArsZertifikatService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ClientCertificate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlgorithmusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApoIkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApoNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AusstellungsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FingerabdruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GueltigBisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GueltigVonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IstAktiviertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] KeyStoreBlobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriennummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZertifikatHashcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ZertifikateBlobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationCode {
            get {
                return this.ActivationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationCodeField, value) != true)) {
                    this.ActivationCodeField = value;
                    this.RaisePropertyChanged("ActivationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Algorithmus {
            get {
                return this.AlgorithmusField;
            }
            set {
                if ((object.ReferenceEquals(this.AlgorithmusField, value) != true)) {
                    this.AlgorithmusField = value;
                    this.RaisePropertyChanged("Algorithmus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApoIk {
            get {
                return this.ApoIkField;
            }
            set {
                if ((this.ApoIkField.Equals(value) != true)) {
                    this.ApoIkField = value;
                    this.RaisePropertyChanged("ApoIk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApoNr {
            get {
                return this.ApoNrField;
            }
            set {
                if ((this.ApoNrField.Equals(value) != true)) {
                    this.ApoNrField = value;
                    this.RaisePropertyChanged("ApoNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ausstellungsdatum {
            get {
                return this.AusstellungsdatumField;
            }
            set {
                if ((this.AusstellungsdatumField.Equals(value) != true)) {
                    this.AusstellungsdatumField = value;
                    this.RaisePropertyChanged("Ausstellungsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fingerabdruck {
            get {
                return this.FingerabdruckField;
            }
            set {
                if ((object.ReferenceEquals(this.FingerabdruckField, value) != true)) {
                    this.FingerabdruckField = value;
                    this.RaisePropertyChanged("Fingerabdruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GueltigBis {
            get {
                return this.GueltigBisField;
            }
            set {
                if ((this.GueltigBisField.Equals(value) != true)) {
                    this.GueltigBisField = value;
                    this.RaisePropertyChanged("GueltigBis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GueltigVon {
            get {
                return this.GueltigVonField;
            }
            set {
                if ((this.GueltigVonField.Equals(value) != true)) {
                    this.GueltigVonField = value;
                    this.RaisePropertyChanged("GueltigVon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IstAktiviert {
            get {
                return this.IstAktiviertField;
            }
            set {
                if ((this.IstAktiviertField.Equals(value) != true)) {
                    this.IstAktiviertField = value;
                    this.RaisePropertyChanged("IstAktiviert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] KeyStoreBlob {
            get {
                return this.KeyStoreBlobField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyStoreBlobField, value) != true)) {
                    this.KeyStoreBlobField = value;
                    this.RaisePropertyChanged("KeyStoreBlob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passwort {
            get {
                return this.PasswortField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswortField, value) != true)) {
                    this.PasswortField = value;
                    this.RaisePropertyChanged("Passwort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seriennummer {
            get {
                return this.SeriennummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriennummerField, value) != true)) {
                    this.SeriennummerField = value;
                    this.RaisePropertyChanged("Seriennummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZertifikatHashcode {
            get {
                return this.ZertifikatHashcodeField;
            }
            set {
                if ((this.ZertifikatHashcodeField.Equals(value) != true)) {
                    this.ZertifikatHashcodeField = value;
                    this.RaisePropertyChanged("ZertifikatHashcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ZertifikateBlob {
            get {
                return this.ZertifikateBlobField;
            }
            set {
                if ((object.ReferenceEquals(this.ZertifikateBlobField, value) != true)) {
                    this.ZertifikateBlobField = value;
                    this.RaisePropertyChanged("ZertifikateBlob");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerCertificate", Namespace="http://schemas.datacontract.org/2004/07/ArsZertifikatService.Contracts")]
    [System.SerializableAttribute()]
    public partial class ServerCertificate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlgorithmusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AusstellungsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FingerabdruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GueltigBisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GueltigVonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IstAktiviertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] KeyStoreBlobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriennummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ZertifikateBlobField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Algorithmus {
            get {
                return this.AlgorithmusField;
            }
            set {
                if ((object.ReferenceEquals(this.AlgorithmusField, value) != true)) {
                    this.AlgorithmusField = value;
                    this.RaisePropertyChanged("Algorithmus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ausstellungsdatum {
            get {
                return this.AusstellungsdatumField;
            }
            set {
                if ((this.AusstellungsdatumField.Equals(value) != true)) {
                    this.AusstellungsdatumField = value;
                    this.RaisePropertyChanged("Ausstellungsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fingerabdruck {
            get {
                return this.FingerabdruckField;
            }
            set {
                if ((object.ReferenceEquals(this.FingerabdruckField, value) != true)) {
                    this.FingerabdruckField = value;
                    this.RaisePropertyChanged("Fingerabdruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GueltigBis {
            get {
                return this.GueltigBisField;
            }
            set {
                if ((this.GueltigBisField.Equals(value) != true)) {
                    this.GueltigBisField = value;
                    this.RaisePropertyChanged("GueltigBis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GueltigVon {
            get {
                return this.GueltigVonField;
            }
            set {
                if ((this.GueltigVonField.Equals(value) != true)) {
                    this.GueltigVonField = value;
                    this.RaisePropertyChanged("GueltigVon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IstAktiviert {
            get {
                return this.IstAktiviertField;
            }
            set {
                if ((this.IstAktiviertField.Equals(value) != true)) {
                    this.IstAktiviertField = value;
                    this.RaisePropertyChanged("IstAktiviert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] KeyStoreBlob {
            get {
                return this.KeyStoreBlobField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyStoreBlobField, value) != true)) {
                    this.KeyStoreBlobField = value;
                    this.RaisePropertyChanged("KeyStoreBlob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passwort {
            get {
                return this.PasswortField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswortField, value) != true)) {
                    this.PasswortField = value;
                    this.RaisePropertyChanged("Passwort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seriennummer {
            get {
                return this.SeriennummerField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriennummerField, value) != true)) {
                    this.SeriennummerField = value;
                    this.RaisePropertyChanged("Seriennummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ZertifikateBlob {
            get {
                return this.ZertifikateBlobField;
            }
            set {
                if ((object.ReferenceEquals(this.ZertifikateBlobField, value) != true)) {
                    this.ZertifikateBlobField = value;
                    this.RaisePropertyChanged("ZertifikateBlob");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sicherheitsmerkmale", Namespace="http://schemas.datacontract.org/2004/07/ArsZertifikatService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Sicherheitsmerkmale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HashfunktionenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SignaturalgorithmenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] VerschluesselungsalgorithmenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Hashfunktionen {
            get {
                return this.HashfunktionenField;
            }
            set {
                if ((object.ReferenceEquals(this.HashfunktionenField, value) != true)) {
                    this.HashfunktionenField = value;
                    this.RaisePropertyChanged("Hashfunktionen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Signaturalgorithmen {
            get {
                return this.SignaturalgorithmenField;
            }
            set {
                if ((object.ReferenceEquals(this.SignaturalgorithmenField, value) != true)) {
                    this.SignaturalgorithmenField = value;
                    this.RaisePropertyChanged("Signaturalgorithmen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Verschluesselungsalgorithmen {
            get {
                return this.VerschluesselungsalgorithmenField;
            }
            set {
                if ((object.ReferenceEquals(this.VerschluesselungsalgorithmenField, value) != true)) {
                    this.VerschluesselungsalgorithmenField = value;
                    this.RaisePropertyChanged("Verschluesselungsalgorithmen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZertifikatService.IArsZertifikatService")]
    public interface IArsZertifikatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArsZertifikatService/ClientZertifikatHinzufuegen", ReplyAction="http://tempuri.org/IArsZertifikatService/ClientZertifikatHinzufuegenResponse")]
        void ClientZertifikatHinzufuegen(byte[] x509cert, byte[] keyStore, string passwort, string pin, string activationCode, bool istAktiviert, int serverZertifikatId, System.DateTime ausstellungsdatum, int apoNr, int apoIk, int zertifikatHashCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArsZertifikatService/ServerZertifikatHinzufuegen", ReplyAction="http://tempuri.org/IArsZertifikatService/ServerZertifikatHinzufuegenResponse")]
        void ServerZertifikatHinzufuegen(byte[] x509cert, byte[] keyStore, string passwort, bool istAktiviert, System.DateTime ausstellungsdatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArsZertifikatService/GetClientZertifikat", ReplyAction="http://tempuri.org/IArsZertifikatService/GetClientZertifikatResponse")]
        FiverxLinkSecurityTestClient.ZertifikatService.ClientCertificate GetClientZertifikat(int apoNr, int apoIk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArsZertifikatService/GetServerZertifikate", ReplyAction="http://tempuri.org/IArsZertifikatService/GetServerZertifikateResponse")]
        FiverxLinkSecurityTestClient.ZertifikatService.ServerCertificate[] GetServerZertifikate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArsZertifikatService/GetSicherheitsmerkmale", ReplyAction="http://tempuri.org/IArsZertifikatService/GetSicherheitsmerkmaleResponse")]
        FiverxLinkSecurityTestClient.ZertifikatService.Sicherheitsmerkmale GetSicherheitsmerkmale();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArsZertifikatServiceChannel : FiverxLinkSecurityTestClient.ZertifikatService.IArsZertifikatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArsZertifikatServiceClient : System.ServiceModel.ClientBase<FiverxLinkSecurityTestClient.ZertifikatService.IArsZertifikatService>, FiverxLinkSecurityTestClient.ZertifikatService.IArsZertifikatService {
        
        public ArsZertifikatServiceClient() {
        }
        
        public ArsZertifikatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArsZertifikatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArsZertifikatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArsZertifikatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClientZertifikatHinzufuegen(byte[] x509cert, byte[] keyStore, string passwort, string pin, string activationCode, bool istAktiviert, int serverZertifikatId, System.DateTime ausstellungsdatum, int apoNr, int apoIk, int zertifikatHashCode) {
            base.Channel.ClientZertifikatHinzufuegen(x509cert, keyStore, passwort, pin, activationCode, istAktiviert, serverZertifikatId, ausstellungsdatum, apoNr, apoIk, zertifikatHashCode);
        }
        
        public void ServerZertifikatHinzufuegen(byte[] x509cert, byte[] keyStore, string passwort, bool istAktiviert, System.DateTime ausstellungsdatum) {
            base.Channel.ServerZertifikatHinzufuegen(x509cert, keyStore, passwort, istAktiviert, ausstellungsdatum);
        }
        
        public FiverxLinkSecurityTestClient.ZertifikatService.ClientCertificate GetClientZertifikat(int apoNr, int apoIk) {
            return base.Channel.GetClientZertifikat(apoNr, apoIk);
        }
        
        public FiverxLinkSecurityTestClient.ZertifikatService.ServerCertificate[] GetServerZertifikate() {
            return base.Channel.GetServerZertifikate();
        }
        
        public FiverxLinkSecurityTestClient.ZertifikatService.Sicherheitsmerkmale GetSicherheitsmerkmale() {
            return base.Channel.GetSicherheitsmerkmale();
        }
    }
}
