//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityLib.WSDL.V0200
{

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ServiceModel.ServiceContractAttribute(Namespace = "http://fiverx.de/security", ConfigurationName = "FiverxLinkSecurityService_PortType")]
  public interface FiverxLinkSecurityService_PortType
  {

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSecurityVersion weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#rzeladeRzSecurityVersion", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ladeRzSecurityVersionResponse ladeRzSecurityVersion(ladeRzSecurityVersionRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#rzeladeRzSecurityVersion", ReplyAction = "*")]
    System.Threading.Tasks.Task<ladeRzSecurityVersionResponse> ladeRzSecurityVersionAsync(ladeRzSecurityVersionRequest request);

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzZertifikat weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#ladeRzZertifikat", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ladeRzZertifikatResponse ladeRzZertifikat(ladeRzZertifikatRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#ladeRzZertifikat", ReplyAction = "*")]
    System.Threading.Tasks.Task<ladeRzZertifikatResponse> ladeRzZertifikatAsync(ladeRzZertifikatRequest request);

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSicherheitsmerkmale weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#ladeRzSicherheitsmerkmale", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmale(ladeRzSicherheitsmerkmaleRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#ladeRzSicherheitsmerkmale", ReplyAction = "*")]
    System.Threading.Tasks.Task<ladeRzSicherheitsmerkmaleResponse> ladeRzSicherheitsmerkmaleAsync(ladeRzSicherheitsmerkmaleRequest request);

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang aktiviereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#aktiviereApothekenZugang", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    aktiviereApothekenZugangResponse aktiviereApothekenZugang(aktiviereApothekenZugangRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#aktiviereApothekenZugang", ReplyAction = "*")]
    System.Threading.Tasks.Task<aktiviereApothekenZugangResponse> aktiviereApothekenZugangAsync(aktiviereApothekenZugangRequest request);

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verlaengereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#verlaengereApothekenZugang", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    verlaengereApothekenZugangResponse verlaengereApothekenZugang(verlaengereApothekenZugangRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#verlaengereApothekenZugang", ReplyAction = "*")]
    System.Threading.Tasks.Task<verlaengereApothekenZugangResponse> verlaengereApothekenZugangAsync(verlaengereApothekenZugangRequest request);

    // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#verarbeiteAuftrag", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    verarbeiteAuftragResponse verarbeiteAuftrag(verarbeiteAuftragRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://fiverx.de/security#verarbeiteAuftrag", ReplyAction = "*")]
    System.Threading.Tasks.Task<verarbeiteAuftragResponse> verarbeiteAuftragAsync(verarbeiteAuftragRequest request);
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/types")]
  public partial class einParameterRequestMsg
  {

    private string rzeEingabeDatenField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string rzeEingabeDaten
    {
      get
      {
        return this.rzeEingabeDatenField;
      }
      set
      {
        this.rzeEingabeDatenField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/types")]
  public partial class zweiParameterRequestMsg
  {

    private string rzeEingabeDatenField;

    private string rzeLadeRzSecurityVersionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string rzeEingabeDaten
    {
      get
      {
        return this.rzeEingabeDatenField;
      }
      set
      {
        this.rzeEingabeDatenField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string rzeLadeRzSecurityVersion
    {
      get
      {
        return this.rzeLadeRzSecurityVersionField;
      }
      set
      {
        this.rzeLadeRzSecurityVersionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/types")]
  public partial class genericResponseMsg
  {

    private string rzeAusgabeDatenField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string rzeAusgabeDaten
    {
      get
      {
        return this.rzeAusgabeDatenField;
      }
      set
      {
        this.rzeAusgabeDatenField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzSecurityVersionRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public einParameterRequestMsg ladeRzSecurityVersionRequestMsg;

    public ladeRzSecurityVersionRequest()
    {
    }

    public ladeRzSecurityVersionRequest(einParameterRequestMsg ladeRzSecurityVersionRequestMsg)
    {
      this.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzSecurityVersionResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg ladeRzSecurityVersionResponseMsg;

    public ladeRzSecurityVersionResponse()
    {
    }

    public ladeRzSecurityVersionResponse(genericResponseMsg ladeRzSecurityVersionResponseMsg)
    {
      this.ladeRzSecurityVersionResponseMsg = ladeRzSecurityVersionResponseMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzZertifikatRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public zweiParameterRequestMsg ladeRzZertifikatRequestMsg;

    public ladeRzZertifikatRequest()
    {
    }

    public ladeRzZertifikatRequest(zweiParameterRequestMsg ladeRzZertifikatRequestMsg)
    {
      this.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzZertifikatResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg ladeRzZertifikatResponseMsg;

    public ladeRzZertifikatResponse()
    {
    }

    public ladeRzZertifikatResponse(genericResponseMsg ladeRzZertifikatResponseMsg)
    {
      this.ladeRzZertifikatResponseMsg = ladeRzZertifikatResponseMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzSicherheitsmerkmaleRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg;

    public ladeRzSicherheitsmerkmaleRequest()
    {
    }

    public ladeRzSicherheitsmerkmaleRequest(zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg)
    {
      this.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class ladeRzSicherheitsmerkmaleResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg;

    public ladeRzSicherheitsmerkmaleResponse()
    {
    }

    public ladeRzSicherheitsmerkmaleResponse(genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg)
    {
      this.ladeRzSicherheitsmerkmaleResponseMsg = ladeRzSicherheitsmerkmaleResponseMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class aktiviereApothekenZugangRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg;

    public aktiviereApothekenZugangRequest()
    {
    }

    public aktiviereApothekenZugangRequest(zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg)
    {
      this.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class aktiviereApothekenZugangResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg aktiviereApothekenZugangResponseMsg;

    public aktiviereApothekenZugangResponse()
    {
    }

    public aktiviereApothekenZugangResponse(genericResponseMsg aktiviereApothekenZugangResponseMsg)
    {
      this.aktiviereApothekenZugangResponseMsg = aktiviereApothekenZugangResponseMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class verlaengereApothekenZugangRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg;

    public verlaengereApothekenZugangRequest()
    {
    }

    public verlaengereApothekenZugangRequest(zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg)
    {
      this.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class verlaengereApothekenZugangResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg verlaengereApothekenZugangResponseMsg;

    public verlaengereApothekenZugangResponse()
    {
    }

    public verlaengereApothekenZugangResponse(genericResponseMsg verlaengereApothekenZugangResponseMsg)
    {
      this.verlaengereApothekenZugangResponseMsg = verlaengereApothekenZugangResponseMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class verarbeiteAuftragRequest
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public zweiParameterRequestMsg verarbeiteAuftragRequestMsg;

    public verarbeiteAuftragRequest()
    {
    }

    public verarbeiteAuftragRequest(zweiParameterRequestMsg verarbeiteAuftragRequestMsg)
    {
      this.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class verarbeiteAuftragResponse
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://fiverx.de/security/types", Order = 0)]
    public genericResponseMsg verarbeiteAuftragResponseMsg;

    public verarbeiteAuftragResponse()
    {
    }

    public verarbeiteAuftragResponse(genericResponseMsg verarbeiteAuftragResponseMsg)
    {
      this.verarbeiteAuftragResponseMsg = verarbeiteAuftragResponseMsg;
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  public interface FiverxLinkSecurityService_PortTypeChannel : FiverxLinkSecurityService_PortType, System.ServiceModel.IClientChannel
  {
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
  public partial class FiverxLinkSecurityService_PortTypeClient : System.ServiceModel.ClientBase<FiverxLinkSecurityService_PortType>, FiverxLinkSecurityService_PortType
  {

    public FiverxLinkSecurityService_PortTypeClient()
    {
    }

    public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName) :
      base(endpointConfigurationName)
    {
    }

    public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, string remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
      base(endpointConfigurationName, remoteAddress)
    {
    }

    public FiverxLinkSecurityService_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
      base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ladeRzSecurityVersionResponse FiverxLinkSecurityService_PortType.ladeRzSecurityVersion(ladeRzSecurityVersionRequest request)
    {
      return base.Channel.ladeRzSecurityVersion(request);
    }

    public genericResponseMsg ladeRzSecurityVersion(einParameterRequestMsg ladeRzSecurityVersionRequestMsg)
    {
      ladeRzSecurityVersionRequest inValue = new ladeRzSecurityVersionRequest();
      inValue.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
      ladeRzSecurityVersionResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).ladeRzSecurityVersion(inValue);
      return retVal.ladeRzSecurityVersionResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ladeRzSecurityVersionResponse> FiverxLinkSecurityService_PortType.ladeRzSecurityVersionAsync(ladeRzSecurityVersionRequest request)
    {
      return base.Channel.ladeRzSecurityVersionAsync(request);
    }

    public System.Threading.Tasks.Task<ladeRzSecurityVersionResponse> ladeRzSecurityVersionAsync(einParameterRequestMsg ladeRzSecurityVersionRequestMsg)
    {
      ladeRzSecurityVersionRequest inValue = new ladeRzSecurityVersionRequest();
      inValue.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).ladeRzSecurityVersionAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ladeRzZertifikatResponse FiverxLinkSecurityService_PortType.ladeRzZertifikat(ladeRzZertifikatRequest request)
    {
      return base.Channel.ladeRzZertifikat(request);
    }

    public genericResponseMsg ladeRzZertifikat(zweiParameterRequestMsg ladeRzZertifikatRequestMsg)
    {
      ladeRzZertifikatRequest inValue = new ladeRzZertifikatRequest();
      inValue.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
      ladeRzZertifikatResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).ladeRzZertifikat(inValue);
      return retVal.ladeRzZertifikatResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ladeRzZertifikatResponse> FiverxLinkSecurityService_PortType.ladeRzZertifikatAsync(ladeRzZertifikatRequest request)
    {
      return base.Channel.ladeRzZertifikatAsync(request);
    }

    public System.Threading.Tasks.Task<ladeRzZertifikatResponse> ladeRzZertifikatAsync(zweiParameterRequestMsg ladeRzZertifikatRequestMsg)
    {
      ladeRzZertifikatRequest inValue = new ladeRzZertifikatRequest();
      inValue.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).ladeRzZertifikatAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ladeRzSicherheitsmerkmaleResponse FiverxLinkSecurityService_PortType.ladeRzSicherheitsmerkmale(ladeRzSicherheitsmerkmaleRequest request)
    {
      return base.Channel.ladeRzSicherheitsmerkmale(request);
    }

    public genericResponseMsg ladeRzSicherheitsmerkmale(zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg)
    {
      ladeRzSicherheitsmerkmaleRequest inValue = new ladeRzSicherheitsmerkmaleRequest();
      inValue.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
      ladeRzSicherheitsmerkmaleResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).ladeRzSicherheitsmerkmale(inValue);
      return retVal.ladeRzSicherheitsmerkmaleResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ladeRzSicherheitsmerkmaleResponse> FiverxLinkSecurityService_PortType.ladeRzSicherheitsmerkmaleAsync(ladeRzSicherheitsmerkmaleRequest request)
    {
      return base.Channel.ladeRzSicherheitsmerkmaleAsync(request);
    }

    public System.Threading.Tasks.Task<ladeRzSicherheitsmerkmaleResponse> ladeRzSicherheitsmerkmaleAsync(zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg)
    {
      ladeRzSicherheitsmerkmaleRequest inValue = new ladeRzSicherheitsmerkmaleRequest();
      inValue.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).ladeRzSicherheitsmerkmaleAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    aktiviereApothekenZugangResponse FiverxLinkSecurityService_PortType.aktiviereApothekenZugang(aktiviereApothekenZugangRequest request)
    {
      return base.Channel.aktiviereApothekenZugang(request);
    }

    public genericResponseMsg aktiviereApothekenZugang(zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg)
    {
      aktiviereApothekenZugangRequest inValue = new aktiviereApothekenZugangRequest();
      inValue.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
      aktiviereApothekenZugangResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).aktiviereApothekenZugang(inValue);
      return retVal.aktiviereApothekenZugangResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<aktiviereApothekenZugangResponse> FiverxLinkSecurityService_PortType.aktiviereApothekenZugangAsync(aktiviereApothekenZugangRequest request)
    {
      return base.Channel.aktiviereApothekenZugangAsync(request);
    }

    public System.Threading.Tasks.Task<aktiviereApothekenZugangResponse> aktiviereApothekenZugangAsync(zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg)
    {
      aktiviereApothekenZugangRequest inValue = new aktiviereApothekenZugangRequest();
      inValue.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).aktiviereApothekenZugangAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    verlaengereApothekenZugangResponse FiverxLinkSecurityService_PortType.verlaengereApothekenZugang(verlaengereApothekenZugangRequest request)
    {
      return base.Channel.verlaengereApothekenZugang(request);
    }

    public genericResponseMsg verlaengereApothekenZugang(zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg)
    {
      verlaengereApothekenZugangRequest inValue = new verlaengereApothekenZugangRequest();
      inValue.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
      verlaengereApothekenZugangResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).verlaengereApothekenZugang(inValue);
      return retVal.verlaengereApothekenZugangResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<verlaengereApothekenZugangResponse> FiverxLinkSecurityService_PortType.verlaengereApothekenZugangAsync(verlaengereApothekenZugangRequest request)
    {
      return base.Channel.verlaengereApothekenZugangAsync(request);
    }

    public System.Threading.Tasks.Task<verlaengereApothekenZugangResponse> verlaengereApothekenZugangAsync(zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg)
    {
      verlaengereApothekenZugangRequest inValue = new verlaengereApothekenZugangRequest();
      inValue.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).verlaengereApothekenZugangAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    verarbeiteAuftragResponse FiverxLinkSecurityService_PortType.verarbeiteAuftrag(verarbeiteAuftragRequest request)
    {
      return base.Channel.verarbeiteAuftrag(request);
    }

    public genericResponseMsg verarbeiteAuftrag(zweiParameterRequestMsg verarbeiteAuftragRequestMsg)
    {
      verarbeiteAuftragRequest inValue = new verarbeiteAuftragRequest();
      inValue.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
      verarbeiteAuftragResponse retVal = ((FiverxLinkSecurityService_PortType)(this)).verarbeiteAuftrag(inValue);
      return retVal.verarbeiteAuftragResponseMsg;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<verarbeiteAuftragResponse> FiverxLinkSecurityService_PortType.verarbeiteAuftragAsync(verarbeiteAuftragRequest request)
    {
      return base.Channel.verarbeiteAuftragAsync(request);
    }

    public System.Threading.Tasks.Task<verarbeiteAuftragResponse> verarbeiteAuftragAsync(zweiParameterRequestMsg verarbeiteAuftragRequestMsg)
    {
      verarbeiteAuftragRequest inValue = new verarbeiteAuftragRequest();
      inValue.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
      return ((FiverxLinkSecurityService_PortType)(this)).verarbeiteAuftragAsync(inValue);
    }
  }
}